### ISSUE TITLE
compatiblity with BTS7960 H-bridge

### ISSUE THREAD

**Issue by waspinator** [alextaujenis/RBD_Motor#1]
Thanks for creating and sharing your suite of libraries. 

Is it possible to use this library to control an H-bridge that only has two pins? So instead of a PWM pin, and forward + reverse pins, only have two PWM pins. For example, if you wanted to move the motor forward, you would set the forward PWM pin to a non-zero value, and the reverse PWM pin to 0. 

![application note](http://i.imgur.com/A6JcViU.png)

http://www.infineon.com/dgdl/Infineon-BTS7960-DS-v01_01-en.pdf?folderId=db3a304412b407950112b408e8c90004&fileId=db3a304412b407950112b43945006d5d&ack=t

**Comment by alextaujenis** [comment]
There are a handful of ways you can control an H-bridge with an Arduino. Right now I don't plan on extending this library to support this configuration. You are welcome to fork this library for your own needs.
