### ISSUE TITLE
rbd-motor + sd-a2dp-player in one program

### ISSUE THREAD

**Issue by yannk0** [alextaujenis/RBD_Motor#4]
for an installation i need the ramp function and arduino-audtio-tools sd-a2dp-player in one sketch. if i do so, with player active, no ramp anymore possible. i need a slow ramp up over 5sec or more when the player starts, slow down when the player stops . something interferes there. how could i get to the core of the problem? where to look?  i am not a real programmer...but experimentalist
yann

**Comment by alextaujenis** [comment]
Can you provide some sample code or list what other libraries you are using? I need a little more context to understand what’s happening here.

**Comment by yannk0** [comment]
of course. attached my (chaos-) sketch. its incomplete. the goal is start the motor slowly ramping up over 5 sec run for some time spin down whlie simultaeously starting the player play random tracks out of a folder and fade out when the motor slows down. it is part of a oundinstallation with three access rotating object with a bt-speaker in its center. it has to spin up slowly because of the moving masses...

what happens now if i press the button the motor just switches full on, the ramp functionality gone...it works normal if i remove the player code. there is an sd card connected via spi.

now i try to hook a nano only for the motor code which also is too big to include wifi later...but that via uart is not flawlessly...yet. the player code also affects uart to have 10 seconds latency

so far the whole thing.



[RBDmotorSdA2dpPlayer.txt](https://github.com/alextaujenis/RBD_Motor/files/7670113/RBDmotorSdA2dpPlayer.txt)
.

**Comment by alextaujenis** [comment]
Solution provided here: https://github.com/alextaujenis/RBD_Motor/issues/5#issuecomment-1099554804
